### ISSUE TITLE
Welcome message on server join

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/discord-bot#13]
### Describe the solution you'd like

An automatic message on member join of the server. This message should outline the steps to connect your Thalia account.

### Motivation

We need to let the people who are joining the server know that they can connect their Thalia account. Without a message that would create a problem where they do not know they have to do this.

**Comment by mark-boute** [comment]
Shouldn't this issue be closed?

**Comment by se-bastiaan** [comment]
Yes
