### ISSUE TITLE
Don't allow connecting multiple times

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/discord-bot#32]
### Is your feature request related to a problem? Please describe.
My concrexit applications show the discord bot 6 times currently.

### Describe the solution you'd like
Let the discord bot check whether I have already connected it.

### Motivation
Keep things clean

### Describe alternatives you've considered
Manually revoking the applications, but I don't know which

**Comment by se-bastiaan** [comment]
@JobDoesburg You can invoke all of them if you want, they are only used for the initial connect
