### ISSUE TITLE
Add a command: !dice [num]

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/discord-bot#37]
### Name

`[prefix]dice [amount:num] [eyes:num]`

where the argument is optional and defaults to 2.

### Description

It should return a random number in `range(1, [eyes] + 1)` for each in `range([amount])`. The result should be sent as a direct response to the dice command and the command does not have to be removed.

### Use cases

Sometimes you just want to play a game. But then you do not have anyone or anything to play a game with. That's where this command comes in.

### Permissions

Everyone may access this command.

### Additional context
Add any other context about the command here.

**Comment by mark-boute** [comment]
I think we should add an optional argument for eyes with default 6

**Comment by se-bastiaan** [comment]
We should also alias this command to `!mexx` which is the same as `!dice 2 6` and `!mexxx` to `!dice 2 2`
