### ISSUE TITLE
Add new command: purge

### ISSUE THREAD

**Issue by megamichiel** [svthalia/discord-bot#46]
### Name
purge ~prune~ [count]

### Description
Remove the last [count] messages in the current channel

### Use cases
Clearing spam from a channel (#boardroom has for instance been spammed with bot commands or other bogus);
Clearing messages from a channel to make room for new conversations.

### Permissions
Moderators should be able to use it.

**Comment by mark-boute** [comment]
I was also planning in implementing this, so I think we'll add it soon.

**Comment by mark-boute** [comment]
The command will be called 'purge' instead. Dutch: 'zuivering', 'reiniging', 'verwijderen'. Whereas 'prune' translates to 'gedroogde pruim', 'snoeien'. (Via Google Translate)

See also: Dyno bot.
