### ISSUE TITLE
Command "member whoami" does not return a correct response.

### ISSUE THREAD

**Issue by lucacastelnuovo** [svthalia/discord-bot#58]
### Describe the bug
ThaliaBot does not respond to `!member whoami` command correctly.

### How to reproduce
Steps to reproduce the behaviour:
1. Open a DM to ThaliaBot
2. Send message `!member whoami`

### Expected behaviour
The expected behaviour is to get receive a meesage from the bot containing my display name and user id.

### Screenshots
<img width="298" alt="screenshot_2020-10-28_at_13 16 43" src="https://user-images.githubusercontent.com/26206253/97435397-a1da0580-1920-11eb-886a-efe801dfaa45.png">

**Comment by se-bastiaan** [comment]
Most likely result of #51
