### ISSUE TITLE
!sync full never finishes

### ISSUE THREAD

**Issue by mark-boute** [svthalia/discord-bot#59]
### Describe the bug
When running `!sync full` the bot never finishes the syn

### How to reproduce
Steps to reproduce the behaviour:
1. Run the bot
2. Run `!sync full`
3. See in the logs that the bot never logs `Periodic member sync complete`

### Expected behaviour
The bot should finish the sync.

**Comment by se-bastiaan** [comment]
![Screenshot 2020-11-07 at 18 31 05](https://user-images.githubusercontent.com/1799914/98447732-6f51b900-2127-11eb-9128-e110aeede30a.png)
I am not able to reproduce on production with current master branch

**Comment by mark-boute** [comment]
Uh same
