### ISSUE TITLE
!sync responds with `Sorry, something went wrong.`

### ISSUE THREAD

**Issue by rowan-vr** [svthalia/discord-bot#66]
### Describe the bug
The `!sync` command responds with `Sorry, something went wrong.`

### How to reproduce
Steps to reproduce the behaviour:
1. Send `!sync` in either the bot's DM's or in the Thalia server
2. Observe the response

### Expected behaviour
It would do the appropriate action of the command, sync the roles of the website, or show you aren't connected

### Screenshots
![image](https://user-images.githubusercontent.com/24590405/139722491-b96dc79b-90f4-4acc-9926-25d954ea9d40.png)

### Additional context
The error is shown when already connected, I'm unsure if it also shows for not connected accounts.

**Comment by se-bastiaan** [comment]
The problem here is that the bot needs to refresh it's authentication token. But it somehow doesn't. And then there is no user attached because the bot is using anonymous login.

**Comment by se-bastiaan** [comment]
Since the bot is now in typescript this is no longer a problem in this form.
